server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/omnicharge_payment
    username: root
    password: user
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
